### ISSUE TITLE
from .build import array

### ISSUE THREAD

**Issue by claudio-ICL** [X-DataInitiative/tick#492]
I am installing `tick` on Ubuntu 22.04 with `pip install tick`. Installation was successful (but it required `swig`). Unfortunately, importing from `tick.hawkes` does not seem to work, because in the `__init__`  of `tick.array` we try to import `array` from `.build` and this is not found. Please see attached. Could you please adise how to resolve the issue?

[error.txt](https://github.com/X-DataInitiative/tick/files/9944281/error.txt)

**Comment by PhilipDeegan** [comment]
Hey @claudio-ICL 

the error you're getting seems to be 

```
_array.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

If you have swig installed on your system you can try building it from source, which possibly will resolve your linking issue (I can't really say for certain sadly)

you can try building from source like this

```
git clone https://github.com/X-DataInitiative/tick
cd tick
python3 setup.py build_ext --inplace
```

I should add if you're using python3.10 or higher you might have an issue which is resolved in an open [PR](https://github.com/X-DataInitiative/tick/pull/483)

**Comment by claudio-ICL** [comment]
Hi @PhilipDeegan 

Thanks for helping!

I am indeed trying to build from source. I do have SWIG and I am using Python 3.6.

Re-building with `python setup.py build_ext --inplace` gives:
`Error executing check_mkl.py - mkl not found
running build_ext
copying build/lib.linux-x86_64-3.6/tick/array/build/_array.cpython-36m-x86_64-linux-gnu.so -> tick/array/build
copying build/lib.linux-x86_64-3.6/tick/base/build/_base.cpython-36m-x86_64-linux-gnu.so -> tick/base/build
copying build/lib.linux-x86_64-3.6/tick/array_test/build/_array_test.cpython-36m-x86_64-linux-gnu.so -> tick/array_test/build
copying build/lib.linux-x86_64-3.6/tick/random/build/_crandom.cpython-36m-x86_64-linux-gnu.so -> tick/random/build
copying build/lib.linux-x86_64-3.6/tick/base_model/build/_base_model.cpython-36m-x86_64-linux-gnu.so -> tick/base_model/build
copying build/lib.linux-x86_64-3.6/tick/linear_model/build/_linear_model.cpython-36m-x86_64-linux-gnu.so -> tick/linear_model/build
copying build/lib.linux-x86_64-3.6/tick/hawkes/simulation/build/_hawkes_simulation.cpython-36m-x86_64-linux-gnu.so -> tick/hawkes/simulation/build
copying build/lib.linux-x86_64-3.6/tick/hawkes/model/build/_hawkes_model.cpython-36m-x86_64-linux-gnu.so -> tick/hawkes/model/build
copying build/lib.linux-x86_64-3.6/tick/hawkes/inference/build/_hawkes_inference.cpython-36m-x86_64-linux-gnu.so -> tick/hawkes/inference/build
copying build/lib.linux-x86_64-3.6/tick/prox/build/_prox.cpython-36m-x86_64-linux-gnu.so -> tick/prox/build
copying build/lib.linux-x86_64-3.6/tick/preprocessing/build/_preprocessing.cpython-36m-x86_64-linux-gnu.so -> tick/preprocessing/build
copying build/lib.linux-x86_64-3.6/tick/robust/build/_robust.cpython-36m-x86_64-linux-gnu.so -> tick/robust/build
copying build/lib.linux-x86_64-3.6/tick/survival/build/_survival.cpython-36m-x86_64-linux-gnu.so -> tick/survival/build
copying build/lib.linux-x86_64-3.6/tick/solver/build/_solver.cpython-36m-x86_64-linux-gnu.so -> tick/solver/build
`

It seems that the check for mkl fails. Can this be the reason? Can you help with that?

**Comment by PhilipDeegan** [comment]
The MKL error is ignorable I think, you seem to have all the libraries built

**Comment by claudio-ICL** [comment]
I did it from scratch in a `conda env` created with the attached `yml` file. Now the issue seems that I cannot include `cereal`? 
`python setup.py build_ext --inplace
Error executing check_mkl.py - mkl not found
running build_ext
building 'tick.array.build._array' extension
swigging lib/swig/tick/array/array_module.i to lib/swig/tick/array/array_module_wrap.cpp
swig -python -py3 -c++ -Ilib/swig -Ilib/include -outdir tick/array/build -DDEBUG_COSTLY_THROW -o lib/swig/tick/array/array_module_wrap.cpp lib/swig/tick/array/array_module.i
C compiler: gcc -pthread -B /home/claudio/anaconda3/envs/tick/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-Iinclude -Iswig -Ilib/third_party/cereal/include -I/home/claudio/anaconda3/envs/tick/lib/python3.6/site-packages/numpy/core/include -I/home/claudio/anaconda3/envs/tick/include/python3.6m -c'
extra options: '-D_FILE_OFFSET_BITS=64 -DPYTHON_LINK -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Ilib/include -DTICK_SPARSE_INDICES_INT32 -std=c++11 -O2 -DNDEBUG -ffast-math -Wall -Werror -DDEBUG_COSTLY_THROW'
gcc: lib/swig/tick/array/array_module_wrap.cpp
gcc: lib/cpp/array/alloc.cpp
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from lib/include/tick/array/basearray.h:6,
                 from lib/include/tick/array/array.h:11,
                 from lib/include/tick/array/carray_python.h:12,
                 from lib/swig/tick/array/array_module_wrap.cpp:2818:
lib/include/tick/array/abstractarray1d2d.h:32:10: fatal error: cereal/cereal.hpp: No such file or directory
   32 | #include <cereal/cereal.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
error: Command "gcc -pthread -B /home/claudio/anaconda3/envs/tick/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude -Iswig -Ilib/third_party/cereal/include -I/home/claudio/anaconda3/envs/tick/lib/python3.6/site-packages/numpy/core/include -I/home/claudio/anaconda3/envs/tick/include/python3.6m -c lib/swig/tick/array/array_module_wrap.cpp -o build/temp.linux-x86_64-3.6/lib/swig/tick/array/array_module_wrap.o -D_FILE_OFFSET_BITS=64 -DPYTHON_LINK -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Ilib/include -DTICK_SPARSE_INDICES_INT32 -std=c++11 -O2 -DNDEBUG -ffast-math -Wall -Werror -DDEBUG_COSTLY_THROW" failed with exit status 1
`

[tick.yml.txt](https://github.com/X-DataInitiative/tick/files/10066709/tick.yml.txt)

**Comment by PhilipDeegan** [comment]
cereal is a submodule in the repo

you can get it with

`git submodule update --init`

alternatively you can get things like this when cloning with 

`git clone $URL --recursive`

**Comment by claudio-ICL** [comment]
Thanks @PhilipDeegan! All solved now :)

**Comment by claudio-ICL** [comment]
To sum up, 

This is what worked on my Ubuntu 22.04.1 LTS, where the `yml` file file is attached: [tick.yml.txt](https://github.com/X-DataInitiative/tick/files/10067138/tick.yml.txt)

1. git clone git@github.com:X-DataInitiative/tick.git

2. #This is required for cereal!
   git submodule update --init 

3. conda create -f ./tick.yml

4. conda develop -n tick .

5. conda activate tick

6. sudo apt-get install swig

7. sudo apt-get install -y autotools-dev automake gawk bison flex

8. Test: python -c "import dill;"

8. python setup.py build_ext --inplace

9. Test: python -c "import tick;"


I believe we can close this issue.
